spring.application.name=lti-accessibility-tool
server.port=8080

# issuer es donde esta corriendo el LMS
moodle.issuer=http://localhost
# auth-url es la URL del LMS que autentica al usuario
moodle.auth-url=http://localhost/mod/lti/auth.php
