spring.application.name=lti-accessibility-tool
server.port=8080

# issuer es donde esta corriendo el LMS
#moodle.issuer=http://localhost
# auth-url es la URL del LMS que autentica al usuario
#moodle.auth-url=http://localhost/mod/lti/auth.php

#moodle.ws.base-url=http://localhost/webservice/rest/server.php
#moodle.ws.token=cf1092c5fc0b5932019915e32a170c1d


# issuer es donde esta corriendo el LMS
moodle.issuer=https://innovalab.moodlecloud.com

# auth-url es la URL del LMS que autentica al usuario
moodle.auth-url=https://innovalab.moodlecloud.com/mod/lti/auth.php

moodle.ws.base-url=https://innovalab.moodlecloud.com/webservice/rest/server.php
moodle.ws.token=8f53f2b7fff1bb696e7d4e501e047383

#app Frontend en React
app.react-url=${FRONT_URL:http://localhost:5173}

firebase.config.file=lti-external-tool-firebase-adminsdk-fbsvc-2a5e705315.json


# Dile a Spring que lance una excepcion si no encuentra un manejador para la ruta
spring.mvc.throw-exception-if-no-handler-found=true
# Desactiva el mapeo de recursos estaticos por defecto para que no interfiera con el 404
spring.web.resources.add-mappings=false

# IA, CLAVE IA (aca se obtiene https://aistudio.google.com/api-keys , por default ingresas y ya te da una
# -tenes que estar logueado previamente en tu cuenta google-)
spring.ai.model.chat=google-genai
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite
spring.ai.google.genai.api-key=${GOOGLE_AI_API_KEY}
